# Importando libs e lendo o dataset

In [1]:
import pandas as pd
import kagglehub

In [2]:
def return_file(file_path):
   from pathlib import Path

   for file in Path(file_path).iterdir():
      if file.is_file():
         return file

In [3]:
# Download latest version
path = kagglehub.dataset_download("lfarhat/brasil-students-scholarship-prouni-20052019")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.10), please consider upgrading to the latest version (1.0.0).
Path to dataset files: C:\Users\felip\.cache\kagglehub\datasets\lfarhat\brasil-students-scholarship-prouni-20052019\versions\1

In [4]:
import pandas as pd

df = pd.read_csv(f"{str(path/return_file(path))}")
df

,ANO_CONCESSAO_BOLSA,CODIGO_EMEC_IES_BOLSA,NOME_IES_BOLSA,TIPO_BOLSA,MODALIDADE_ENSINO_BOLSA,NOME_CURSO_BOLSA,NOME_TURNO_CURSO_BOLSA,CPF_BENEFICIARIO_BOLSA,SEXO_BENEFICIARIO_BOLSA,RACA_BENEFICIARIO_BOLSA,DT_NASCIMENTO_BENEFICIARIO,BENEFICIARIO_DEFICIENTE_FISICO,REGIAO_BENEFICIARIO_BOLSA,SIGLA_UF_BENEFICIARIO_BOLSA,MUNICIPIO_BENEFICIARIO_BOLSA,idade
0,2005,423,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Enfermagem,Integral,***264740**,F,Branca,1987-02-17,nao,SUL,RS,santo angelo,34.0
1,2005,423,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Servico Social,Noturno,***976940**,F,Parda,1986-06-14,nao,SUL,RS,frederico westphalen,35.0
2,2005,423,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Servico Social,Noturno,***045340**,F,Parda,1984-06-03,nao,SUL,RS,frederico westphalen,37.0
3,2005,423,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Ciencia Da Computacao,Noturno,***988420**,M,Branca,1987-10-19,nao,SUL,RS,frederico westphalen,33.0
4,2005,423,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Ciencia Da Computacao,Noturno,***378080**,M,Amarela,1987-07-20,nao,SUL,RS,frederico westphalen,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2692535,2019,18978,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,FarmAcia,Noturno,***70755437**,F,Parda,2001-04-05,nao,NORDESTE,PE,santa terezinha,20.0
2692536,2019,18978,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Matutino,***23845493**,F,Parda,2001-06-16,nao,NORDESTE,PB,aroeiras,20.0
2692537,2019,18978,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Matutino,***62578423**,M,Branca,1992-12-13,nao,NORDESTE,PB,campina grande,28.0
2692538,2019,18978,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Noturno,***21568498**,F,Parda,1996-12-27,nao,NORDESTE,PB,lagoa seca,24.0
2692539,2019,18978,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,Medicina VeterinAria,Matutino,***34469421**,M,Branca,1985-03-14,nao,NORDESTE,PB,campina grande,36.0

In [5]:
df.isna().sum()

ANO_CONCESSAO_BOLSA                  0
CODIGO_EMEC_IES_BOLSA                0
NOME_IES_BOLSA                     489
TIPO_BOLSA                           0
MODALIDADE_ENSINO_BOLSA              0
NOME_CURSO_BOLSA                  5654
NOME_TURNO_CURSO_BOLSA               0
CPF_BENEFICIARIO_BOLSA               0
SEXO_BENEFICIARIO_BOLSA              0
RACA_BENEFICIARIO_BOLSA              0
DT_NASCIMENTO_BENEFICIARIO           0
BENEFICIARIO_DEFICIENTE_FISICO       0
REGIAO_BENEFICIARIO_BOLSA          402
SIGLA_UF_BENEFICIARIO_BOLSA        402
MUNICIPIO_BENEFICIARIO_BOLSA       402
idade                                0
dtype: int64

In [6]:
df.shape

(2692540, 16)

In [7]:
lista_colunas = df.columns
print(lista_colunas)

Index(['ANO_CONCESSAO_BOLSA', 'CODIGO_EMEC_IES_BOLSA', 'NOME_IES_BOLSA',
       'TIPO_BOLSA', 'MODALIDADE_ENSINO_BOLSA', 'NOME_CURSO_BOLSA',
       'NOME_TURNO_CURSO_BOLSA', 'CPF_BENEFICIARIO_BOLSA',
       'SEXO_BENEFICIARIO_BOLSA', 'RACA_BENEFICIARIO_BOLSA',
       'DT_NASCIMENTO_BENEFICIARIO', 'BENEFICIARIO_DEFICIENTE_FISICO',
       'REGIAO_BENEFICIARIO_BOLSA', 'SIGLA_UF_BENEFICIARIO_BOLSA',
       'MUNICIPIO_BENEFICIARIO_BOLSA', 'idade'],
      dtype='object')

In [8]:
lista_renomeada = [col.upper().replace('_BOLSA', '').replace('NOME_', '').replace('_CURSO_', '').replace('BENEFICIARIO_', '').replace('_BENEFICIARIO', '').replace('_CURSO', '').replace('CURSO_', '').replace('SIGLA_', '').replace('IES', 'INSTITUICAO') for col in lista_colunas]
print(lista_renomeada)

['ANO_CONCESSAO', 'CODIGO_EMEC_INSTITUICAO', 'INSTITUICAO', 'TIPO', 'MODALIDADE_ENSINO', 'CURSO', 'TURNO', 'CPF', 'SEXO', 'RACA', 'DT_NASCIMENTO', 'DEFICIENTE_FISICO', 'REGIAO', 'UF', 'MUNICIPIO', 'IDADE']

In [9]:
df_renamed = df.copy()
df_renamed.rename(columns=dict(zip(lista_colunas, lista_renomeada)), inplace=True)
df_renamed.columns

Index(['ANO_CONCESSAO', 'CODIGO_EMEC_INSTITUICAO', 'INSTITUICAO', 'TIPO',
       'MODALIDADE_ENSINO', 'CURSO', 'TURNO', 'CPF', 'SEXO', 'RACA',
       'DT_NASCIMENTO', 'DEFICIENTE_FISICO', 'REGIAO', 'UF', 'MUNICIPIO',
       'IDADE'],
      dtype='object')

In [10]:
df_renamed.isna().sum()

ANO_CONCESSAO                 0
CODIGO_EMEC_INSTITUICAO       0
INSTITUICAO                 489
TIPO                          0
MODALIDADE_ENSINO             0
CURSO                      5654
TURNO                         0
CPF                           0
SEXO                          0
RACA                          0
DT_NASCIMENTO                 0
DEFICIENTE_FISICO             0
REGIAO                      402
UF                          402
MUNICIPIO                   402
IDADE                         0
dtype: int64

In [25]:
df_limpo = df_renamed.copy()
df_limpo = df_limpo.dropna()

In [26]:
df_limpo.isna().sum()

ANO_CONCESSAO              0
CODIGO_EMEC_INSTITUICAO    0
INSTITUICAO                0
TIPO                       0
MODALIDADE_ENSINO          0
CURSO                      0
TURNO                      0
CPF                        0
SEXO                       0
RACA                       0
DT_NASCIMENTO              0
DEFICIENTE_FISICO          0
REGIAO                     0
UF                         0
MUNICIPIO                  0
IDADE                      0
dtype: int64

In [27]:
lista_apagar = ['CODIGO_EMEC_INSTITUICAO','CPF','DT_NASCIMENTO']
df_limpo = df_limpo.drop(columns=lista_apagar, axis=1)
df_limpo

,ANO_CONCESSAO,INSTITUICAO,TIPO,MODALIDADE_ENSINO,CURSO,TURNO,SEXO,RACA,DEFICIENTE_FISICO,REGIAO,UF,MUNICIPIO,IDADE
0,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Enfermagem,Integral,F,Branca,nao,SUL,RS,santo angelo,34.0
1,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Servico Social,Noturno,F,Parda,nao,SUL,RS,frederico westphalen,35.0
2,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Servico Social,Noturno,F,Parda,nao,SUL,RS,frederico westphalen,37.0
3,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Ciencia Da Computacao,Noturno,M,Branca,nao,SUL,RS,frederico westphalen,33.0
4,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Ciencia Da Computacao,Noturno,M,Amarela,nao,SUL,RS,frederico westphalen,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2692535,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,FarmAcia,Noturno,F,Parda,nao,NORDESTE,PE,santa terezinha,20.0
2692536,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Matutino,F,Parda,nao,NORDESTE,PB,aroeiras,20.0
2692537,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Matutino,M,Branca,nao,NORDESTE,PB,campina grande,28.0
2692538,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Noturno,F,Parda,nao,NORDESTE,PB,lagoa seca,24.0
2692539,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,Medicina VeterinAria,Matutino,M,Branca,nao,NORDESTE,PB,campina grande,36.0

In [28]:
lista_unicos = list(df_limpo["TIPO"].unique())
lista_unicos

['BOLSA PARCIAL 50%', 'BOLSA INTEGRAL', 'BOLSA COMPLEMENTAR 25%']

In [29]:
df_limpo = df_limpo.copy()
df_limpo = df_limpo[(df_limpo['IDADE'] <= 90) & (df_limpo['IDADE'] >= 15)]
#df_limpo.head()
pd.DataFrame(df_limpo.sort_values('IDADE')['IDADE'].unique())

       0
0   15.0
1   16.0
2   17.0
3   18.0
4   19.0
..   ...
71  86.0
72  87.0
73  88.0
74  89.0
75  90.0

[76 rows x 1 columns]

In [30]:
lista_unicos = list(df_limpo["TIPO"].unique())
lista_unicos

['BOLSA PARCIAL 50%', 'BOLSA INTEGRAL', 'BOLSA COMPLEMENTAR 25%']

In [17]:
# df_renamed_ml['Tipo'] = df_renamed_ml['Tipo'].replace({'BOLSA INTEGRAL': 0,'BOLSA PARCIAL 50%': 1,'BOLSA COMPLEMENTAR 25%': 2})
# df_renamed_ml['Modalidade de ensino'] = df_renamed_ml['Modalidade de ensino'].replace({'INTEGRAL': 0,'EAD':1})
# df_renamed_ml['Turno'] = df_renamed_ml['Turno'].replace({'Integral': 0,'Matutino': 1, 'Vespertino': 2, 'Noturno': 3, 'A Distancia': 4})
# df_renamed_ml['Deficiente físico'] = df_renamed_ml['Deficiente físico'].replace({'nao': 0,'sim': 1})
# df_renamed_ml['Raça'] = df_renamed_ml['Raça'].replace({'Branca': 0, 'Parda': 1, 'Amarela': 2, 'Preta': 3, 'Indigena': 4,'Nao Informada': 5})

In [31]:
lista_colunas = df_limpo.columns
lista_colunas

Index(['ANO_CONCESSAO', 'INSTITUICAO', 'TIPO', 'MODALIDADE_ENSINO', 'CURSO',
       'TURNO', 'SEXO', 'RACA', 'DEFICIENTE_FISICO', 'REGIAO', 'UF',
       'MUNICIPIO', 'IDADE'],
      dtype='object')

In [32]:
#lista_renomeada = [col.replace('_', ' ').upper() for col in lista_colunas]
lista_renomeada = ['ANO DE CONCESSÃO', 'INSTITUIÇÃO', 'TIPO DE BOLSA','MODALIDADE DE ENSINO','CURSO','TURNO','SEXO','RAÇA','DEFICIENTE FÍSICO','REGIÃO','UF','MUNICÍPIO','IDADE']
df_limpo.rename(columns=dict(zip(lista_colunas, lista_renomeada)), inplace=True)
df_limpo.columns

Index(['ANO DE CONCESSÃO', 'INSTITUIÇÃO', 'TIPO DE BOLSA',
       'MODALIDADE DE ENSINO', 'CURSO', 'TURNO', 'SEXO', 'RAÇA',
       'DEFICIENTE FÍSICO', 'REGIÃO', 'UF', 'MUNICÍPIO', 'IDADE'],
      dtype='object')

In [33]:
df_limpo = df_limpo[df_limpo['TIPO DE BOLSA'] != 'BOLSA COMPLEMENTAR 25%']
df_limpo

,ANO DE CONCESSÃO,INSTITUIÇÃO,TIPO DE BOLSA,MODALIDADE DE ENSINO,CURSO,TURNO,SEXO,RAÇA,DEFICIENTE FÍSICO,REGIÃO,UF,MUNICÍPIO,IDADE
0,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Enfermagem,Integral,F,Branca,nao,SUL,RS,santo angelo,34.0
1,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Servico Social,Noturno,F,Parda,nao,SUL,RS,frederico westphalen,35.0
2,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Servico Social,Noturno,F,Parda,nao,SUL,RS,frederico westphalen,37.0
3,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Ciencia Da Computacao,Noturno,M,Branca,nao,SUL,RS,frederico westphalen,33.0
4,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Ciencia Da Computacao,Noturno,M,Amarela,nao,SUL,RS,frederico westphalen,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2692535,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,FarmAcia,Noturno,F,Parda,nao,NORDESTE,PE,santa terezinha,20.0
2692536,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Matutino,F,Parda,nao,NORDESTE,PB,aroeiras,20.0
2692537,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Matutino,M,Branca,nao,NORDESTE,PB,campina grande,28.0
2692538,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Noturno,F,Parda,nao,NORDESTE,PB,lagoa seca,24.0
2692539,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,Medicina VeterinAria,Matutino,M,Branca,nao,NORDESTE,PB,campina grande,36.0

In [35]:
df_limpo['IDADE'] = df_limpo['IDADE'].astype(int)

In [36]:
df_limpo

,ANO DE CONCESSÃO,INSTITUIÇÃO,TIPO DE BOLSA,MODALIDADE DE ENSINO,CURSO,TURNO,SEXO,RAÇA,DEFICIENTE FÍSICO,REGIÃO,UF,MUNICÍPIO,IDADE
0,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Enfermagem,Integral,F,Branca,nao,SUL,RS,santo angelo,34
1,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Servico Social,Noturno,F,Parda,nao,SUL,RS,frederico westphalen,35
2,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Servico Social,Noturno,F,Parda,nao,SUL,RS,frederico westphalen,37
3,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Ciencia Da Computacao,Noturno,M,Branca,nao,SUL,RS,frederico westphalen,33
4,2005,UNIVERSIDADE REGIONAL INTEGRADA DO ALTO URUGUA...,BOLSA PARCIAL 50%,PRESENCIAL,Ciencia Da Computacao,Noturno,M,Amarela,nao,SUL,RS,frederico westphalen,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2692535,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,FarmAcia,Noturno,F,Parda,nao,NORDESTE,PE,santa terezinha,20
2692536,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Matutino,F,Parda,nao,NORDESTE,PB,aroeiras,20
2692537,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Matutino,M,Branca,nao,NORDESTE,PB,campina grande,28
2692538,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,GestAo De Recursos Humanos,Noturno,F,Parda,nao,NORDESTE,PB,lagoa seca,24
2692539,2019,FACULDADE REBOUAAS DE CAMPINA GRANDE,BOLSA INTEGRAL,PRESENCIAL,Medicina VeterinAria,Matutino,M,Branca,nao,NORDESTE,PB,campina grande,36

In [37]:
import os
os.makedirs('../data/processed', exist_ok=True)

df_limpo.to_csv('../data/processed/prouni_2005_2019_processed.csv', index=False)